version: '3.6'
services:
  database:
    image: mysql:8.0.31
    ports:
      - "13306:3306"
    container_name: database
    network_mode: "default"
    environment:
        MYSQL_ROOT_PASSWORD: "teodiomysql"
    volumes:
      - ./local_db:/var/lib/mysql
    restart: 'always'
  
  create_database:
    build:
      context: ./create_database
      args:
        - DATABASE_IP=$DATABASE_IP 
    network_mode: "default"